---
title: "Gov 50 Final Project"
description: |
  

author:
  - name: Mashal Farrukh 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Project thoughts

I am interested in exploring the relationship between religious practice, party affliations, on people's attitude towards COVID restrictions and political views. 


```{r}
library(tidyverse)
library(readr)
```

```{r}
Rel_cov <- ATP_W70 |> select (F_ATTEND, COVIDRF_W70, ATTENDMONTH_W70, ATTENDONLINE_W70, ATTENDFUT1_W70, ATTENDFUT2_W70, COVIDCONG2_W70, COVIDCONG3_W70, COVIDCONG4_W70, CONGRESTRICT1_a_W70, CONGRESTRICT1_b_W70, CONGRESTRICT1_c_W70, CONGRESTRICT1_d_W70, CONGRESTRICT2_a_W70, CONGRESTRICT2_b_W70, CONGRESTRICT2_c_W70, CONGRESTRICT2_d_W70, ATTENDCONF_W70, CONGDONATE_W70, ONLINESERV_W70, SERMONISSUE_a_W70, SERMONISSUE_b_W70, SERMONISSUE_c_W70, SERMONISSUE_d_W70, SERMONISSUE_e_W70,SERMONISSUE_f_W70, SERMONISSUE_g_W70, SERMONTRUMP_W70, SERMONBIDEN_W70, COVIDLESSON1_W70, COVIDLESSON2_W70, PARTY_W70, PARTYLN_W70, PARTYSTR_W70) |>mutate(Opinions_on_SD = case_when(COVIDCONG4_W70 == 1 ~ "Open", COVIDCONG4_W70 == 2 ~ "Open with restictions", COVIDCONG4_W70 == 3 ~ "Closed"))
```


```{r}
Opinions <- Rel_cov |>mutate (PARTY_affliation = case_when(PARTY_W70 == 1 ~ "Republican", PARTY_W70 == 2 ~ "Democrat", PARTY_W70 == 3 ~ "Independent", PARTY_W70 == 4 ~ "Something else")) |> group_by( PARTY_affliation, Opinions_on_SD) |> summarise(n= n()) |> mutate (prop = n/ sum(n)) |> drop_na( PARTY_affliation, Opinions_on_SD)


Opinions_plot <- Opinions |> ggplot(aes(x = Opinions_on_SD, y = prop, fill = PARTY_affliation)) + geom_col() + labs( X= "opinions on what the operatings status of places of worship should be according to Party affliation")

Opinions_plot
```
